setwd("")
venn_dat<-read.delim('all.txt', header = T, sep = '\t', stringsAsFactors = F, check.names = F)
BS<-read.delim('BS.txt', header = F, sep = '\t', stringsAsFactors = F, check.names = F)
SA<-read.delim('SA.txt', header = F, sep = '\t', stringsAsFactors = F, check.names = F)
IA<-read.delim('IA.txt', header = F, sep = '\t', stringsAsFactors = F, check.names = F)
DA<- read.delim('DA.txt', header = F, sep = '\t', stringsAsFactors = F, check.names = F)
venn_list <- list(BS[,1], SA[,1],IA[,1],DA[,1])
names(venn_list) <- colnames(venn_dat)
library(VennDiagram)
P<-venn.diagram(venn_list, filename = 'venn(phylum).png', imagetype = 'png', margin = 0.2, alpha = 0.50, col = c('#F08228', '#006BAC','#82D0FF','#F4A666'), cex = 1, fontfamily = 'serif', cat.col = c('#F08228', '#006BAC','#82D0FF','#F4A666'), cat.cex = 1, cat.fontfamily = 'serif')
